baseURL: https://thecommandbook.clox.nu/
languageCode: cn
defaultContentLanguage: cn
title: The Command Book
theme: book

disqusShortname: thecommandbook-clox-nu
publishdir: ../docs/

menu:
  after:
    - name: "关于我"
      url: "https://clox.nu/"
      weight: 1

params:
  BookTheme: "auto"
  BookToc: true
  BookMenuBundle: /menu
  BookRepo: https://github.com/cloxnu/thecommandbook.clox.nu
  BookEditPath: edit/main/src
  BookComments: true
